### ISSUE TITLE
The method used by this program to detect a vWii doesn't work

### ISSUE THREAD

**Issue by pcem-maintainer** [DarkMatterCore/xyzzy-mod#1]
With my fully updated Wii U (with no modifications other than haxchi on the Wii U and HBC on the vWii), this program can't detect that it is running under vWii and exits early when dumping the SEEPROM fails. I've had to recompile it with the vWii check always returning true to make it work.

**Comment by DarkMatterCore** [comment]
I'll look into this matter as soon as I can. Thanks for reporting it. Would you be able to test some test builds? I never got the chance to own a Wii U.

This also means I'll have to update bluedump-mod, since it uses the same detection method.

**Comment by DarkMatterCore** [comment]
@eluancm Should be fixed with the latest commit.
