### ISSUE TITLE
Wii U / vWii detection fails.

### ISSUE THREAD

**Issue by YaketyJoe** [DarkMatterCore/xyzzy-mod#2]
Hola! I am getting the same error as the previously closed issue. I noticed that when downloading the boot.dol from here, the program launched says 1.2.3 on the top, instead of 1.2.4. 

Was the latest boot.dol (1.2.4) submitted on github? If so, how do I download it. I always keep getting 1.2.3 which does not work on WiiU.

Gracias!

**Comment by DarkMatterCore** [comment]
Hi there. The boot.dol binary available in the repository is really v1.2.4 - I probably just forgot to change the version tag before building it.

The Wii U / vWii detection method used here is still the same old one that depends on reading the value from a volatile memory address at runtime. For some reason I don't know, it stopped working at some point - and I never owned a Wii U, so I couldn't perform any additional tests on my own.

I'll need to port the detection method used in YABDM, which relies on the availability of IOS512.

**Comment by DarkMatterCore** [comment]
@YaketyJoe 

Nevermind, I had already ported the IOS512 detection method. D'oh.

I just took the chance to rewrite the application in a better way. I have already pushed my latest changes. Please test the v1.2.5 binary and let me know how it goes.

**Comment by YaketyJoe** [comment]
Thanks for the quick responses! I tried v1.2.5 (unofficial) and it ran when I added the meta,xml from the previous version. It displays this on upper right: IOS58(v6432)

However, I still got an error:
Getting Keys... "Fatal Error: OTP_ReadData() failed."

**Comment by YaketyJoe** [comment]
I also saw all the 1.2.5 binary and xml that you just pushed,  and tried those too. But got the same error.

**Comment by DarkMatterCore** [comment]
@YaketyJoe 

Thanks for the quick response. I believe I know why it's failing - please test this binary and let me know if this one works.

[boot.zip](https://github.com/DarkMatterCore/xyzzy-mod/files/4080079/boot.zip)

**Comment by YaketyJoe** [comment]
Yes, that worked!

v.1.2.6 ran without errors and produced the keys.txt file.

Muchas gracias desde Puerto Rico!

**Comment by DarkMatterCore** [comment]
¡Gracias a ti por reportar el problema y probar los cambios! 😊
