### ISSUE TITLE
Otp and seeprom full dump in a file

### ISSUE THREAD

**Issue by buggii** [DarkMatterCore/xyzzy-mod#3]
Is it possible to have an otp and seeprom full dump in separate .bin files (raw hex values)? It will be a very good thing of You want to append the 1024 bytes footer to a raw nand+ecc dump Made with RealWnD_mini to make it a bootmi-like dump: this will allow to use already made pc tools tools to explore/extract the nand (and Maybe to reflash it in a possible future bootmii-wiimini-compatible version).

**Comment by DarkMatterCore** [comment]
Hi there, mate. Thanks for opening this feature request.

It is indeed possible. I'll get on it right away. Would you be able to test it?

**Comment by DarkMatterCore** [comment]
@buggii Here's a test build, it should be able to generate `otp.bin`, `seeprom.bin` and `bootmii_keys.bin` files in the root directory from the selected storage device. Please let me know how it goes.

[xyzzy_20200507_t1.zip](https://github.com/DarkMatterCore/xyzzy-mod/files/4591168/xyzzy_20200507_t1.zip)

**Comment by buggii** [comment]
It works great ! 

I obtained: bootmii_key.bin - keys.txt - otp.bin - seeprom.bin

Thank you !

**Comment by DarkMatterCore** [comment]
No problem mate. Just pushed the new version. :)

Thanks for testing.
